Improved documentation for Processing Development Environment (PDE)
processing/processing-website pull request #423
Opened 2023-01-30 06:52 UTC by Arya-Gupta

Issue: https://github.com/processing/processing-website/issues/422

Fixed grammatical errors in the [environment page](https://processing.org/environment).

Signed-off-by: Arya Gupta <arya.gupta99999@gmail.com>

2023-01-31 16:33 UTC, SableRaf requested changes
Added a couple of small fixes. Otherwise all good! Thanks for your contribution :)

2023-01-31 16:33 UTC, SableRaf commented on content/pages/environment/index.mdx
> +Sketches can draw two- and three-dimensional graphics. The default renderer is for drawing two-dimensional graphics. The P3D renderer makes it possible to draw three-dimensional graphics, which inclu
I believe this "includes" refers to the ability of P3D to render 3D graphics and not to the phrase "three-dimensional graphics" itself, and therefore should keep its 's'

2023-01-31 16:33 UTC, SableRaf commented on content/pages/environment/index.mdx
> +The Processing Development Environment (PDE) is highly configurable. The most common preferences can be modified in the Preferences window, located in the File menu on Windows and Linux and the Proce
'macOS' is not called X anymore. Just 'macOS'

2023-02-02 12:57 UTC, Arya-Gupta commented
@SableRaf updated!

2023-02-02 15:13 UTC, SableRaf requested changes

2023-02-02 15:13 UTC, SableRaf commented on content/pages/environment/index.mdx
> +    Processing menu on Mac OS.)
Thanks for the update! Small nitpick: it should be styled as **macOS**

2023-02-03 11:16 UTC, SableRaf commented on content/pages/environment/index.mdx
> +The Processing Development Environment (PDE) is highly configurable. The most common preferences can be modified in the Preferences window, located in the File menu on Windows and Linux and the Proce
@Arya-Gupta there is still this one thing pending. After that I'll happily merge your changes :)

2023-02-06 14:14 UTC, SableRaf approved these changes
Great, thanks for your contribution! ✨

2023-02-06 14:14 UTC, merged