making some links to open in a new tab
processing/processing-website pull request #439
Opened 2023-02-11 09:32 UTC by Dev-Code24

This PR is made because of issue: #438 
I have made some changes to all anchor elements where the links should have been opening on a new tab.
The following files have been modified: 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/97425135/218251043-7193c5f1-fafc-4816-b567-e2c2d77d548d.png">

BEFORE:
The following lin
<img width="1680" alt="Screenshot 2023-02-11 at 14 07 24" src="https://user-images.githubusercontent.com/97425135/218251091-d2c24dcb-d2cd-43da-9ff8-53449cf7cd32.png">
<img width="846" alt="Screenshot 2023-02-11 at 14 06 42" src="https://user-images.githubusercontent.com/97425135/218251094-57c012ee-d597-4b25-af43-77c28a442643.png">
ks should be opened on a new tab when clicked:

AFTER:
These links now open in a new tab

2023-02-12 16:45 UTC, Dev-Code24 commented
I have solved issue #427 in the second commit that I made.

@SableRaf pls check the PR.

2023-02-12 16:47 UTC, Dev-Code24 commented
The changes that I made while creating the second PR: 
Before:
<img width="1680" alt="B1" src="https://user-images.githubusercontent.com/97425135/218324546-50338e9f-eb1c-4f5e-81b1-04da9c404025.png">

![B2](https://user-images.githubusercontent.com/97425135/218324608-addfeb61-612a-4916-9190-c7e4df801067.PNG)
![B3](https://user-images.githubusercontent.com/97425135/218324619-955b88ca-15ef-4299-be58-bdb407a74301.PNG)
<img width="996" alt="B4" src="https://user-images.githubusercontent.com/97425135/218324624-21efa18c-1430-41a3-b457-3b7c6986ea3d.png">
![B5](https://user-images.githubusercontent.com/97425135/218324626-a5c9e05d-2b1a-4493-9e6f-07b4108a9f2b.PNG)


After:

<img width="1680" alt="A1" src="https://user-images.githubusercontent.com/97425135/218324640-2e1affce-27ad-4107-9946-b4f88ff21580.png">
![A2](https://user-images.githubusercontent.com/97425135/218324643-718fa361-8930-48d7-9517-e94312e135ed.PNG)
![A3](https://user-images.githubusercontent.com/97425135/218324644-eb538b67-ce13-4b60-8302-c38b3bfd7b62.PNG)
<img width="975" alt="A4" src="https://user-images.githubusercontent.com/97425135/218324645-87584a6a-6d27-4576-88ef-50be743af2a4.png">
![A5](https://user-images.githubusercontent.com/97425135/218324646-2c18913c-c5b9-4644-a328-d4c95a92caf7.PNG)

2023-02-12 16:50 UTC, Dev-Code24 commented
The changes that I made for the second commit are:

Before:

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/97425135/218324710-53194853-52a6-4f0a-8f5b-0547bd11bfa2.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/97425135/218324727-1ea510dd-5bda-499d-ba0c-d676fa004f5f.png">

<img width="244" alt="image" src="https://user-images.githubusercontent.com/97425135/218324745-6afe62de-98fd-474a-96e9-cc6f14421b40.png">

<img width="950" alt="image" src="https://user-images.githubusercontent.com/97425135/218324757-30d15dc7-0314-43ef-be0f-d0ebe1a9edc2.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/97425135/218324764-374695b9-fe13-4489-81b8-7677add7e08c.png">

After:

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/97425135/218324776-e4e6bd9a-636e-4849-ba2c-4c35f3132760.png">

<img width="375" alt="image" src="https://user-images.githubusercontent.com/97425135/218324784-160fa6f1-c576-46e4-b136-de05f8e082f4.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/97425135/218324792-c9bafe8e-0624-4317-8c60-7e52cfcc0d7a.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/97425135/218324799-73a84657-78ae-477d-af87-1356f483af6d.png">

<img width="483" alt="image" src="https://user-images.githubusercontent.com/97425135/218324809-bc988eac-9740-4002-a3cc-8d22c2795f39.png">

2023-02-13 16:34 UTC, fdoflorenzano reviewed
Hi! The parts that affect the links look OK to me, but I can't really comment on the contrast issues cause this would need to go through a more extensive review than just adding a couple colors and changing them in a couple places. Also it looks like there's other people working on the second part #441

2023-02-13 16:39 UTC, Dev-Code24 commented
> 
yeah I also thought that the review would take time, and the part where other people are also working is i guess that person didn't see that i already made a PR and commit regarding the same issue plus tagged the issue too.

2023-02-13 16:57 UTC, SableRaf commented
Hi @Dev-Code24, it's great to see you working on this! To keep things organized and manageable, it would be best to limit each Pull Request to addressing one specific issue. This way, we can keep track of progress and make sure each issue is thoroughly addressed. Thanks for your understanding and efforts!

2023-02-13 17:00 UTC, SableRaf requested changes
Please limit this PR to solving issue https://github.com/processing/processing-website/issues/438 and I will merge it. Thank you for your contribution!

2023-02-13 17:05 UTC, Dev-Code24 commented
> 

ok @SableRaf i'll limit this PR to the issue #438

2023-02-13 17:16 UTC, SableRaf approved these changes

2023-02-13 17:16 UTC, merged

2023-02-13 17:16 UTC, SableRaf commented
Thanks @Dev-Code24 ✨