fixes Facebook link in footer
processing/processing-website pull request #594
Opened 2024-12-22 11:05 UTC by twisst

2024-12-22 11:09 UTC, SableRaf requested changes
The link was incorrect but we have a new dedicated Facebook page for Processing:
https://www.facebook.com/people/Processing-Core/

2024-12-22 11:55 UTC, twisst commented
> https://www.facebook.com/people/Processing-Core/

Could be me but that link leads to a 'not available' page. Maybe it is set to private?

2024-12-22 18:25 UTC, SableRaf commented
Hmm, it is visible to some people at least—posts are getting reactions—but it is possible you need to be logged in to see it according to [this help article](https://www.facebook.com/help/537592652938493/).

> If your Page has age or country restrictions, you won't be able to see it when you're logged out of Facebook.
>
> To see your Page when you're logged out, you'll need to remove all age and country restrictions:

I'll investigate these settings.

2024-12-22 18:44 UTC, SableRaf commented
Everything is set to public and there are no age nor country restrictions. 

Looks like I just got the wrong link. Could you try this one?

https://www.facebook.com/people/Processing-Core/61567491443061/

2024-12-22 20:50 UTC, twisst commented
> https://www.facebook.com/people/Processing-Core/61567491443061/

That page does open! When I open the main link, I just see this:
<img width="607" alt="afbeelding" src="https://github.com/user-attachments/assets/597a771e-6076-4514-b2d7-8d67f01a0e0e" />

And that's also what I see when I try to open it from a private browsing window and whether I am logged in or not. When not logged in I do see the page of the link above behind the log-in window, but not so with the main page. So strange.

2024-12-23 11:24 UTC, SableRaf commented
Strange! For me that link works even in an incognito window

![image](https://github.com/user-attachments/assets/e3e64089-a307-4e2d-be60-034bb7ec8f89)

2024-12-24 12:54 UTC, SableRaf requested changes
Hey @twisst I think you might have included these changes in the "fixes Facebook link in footer" PR by mistake. 

In fact, most of these changes can't be made directly in the website repository anyway. For example, the **contributions**, **reference**, and **examples** are all generated from other sources. See: the [Page content](https://github.com/processing/processing-website?tab=readme-ov-file#page-content) section of the README. 

This whole system is a bit convoluted, so it's completely understandable. If you have any questions or need assistance, feel free to reach out :)

Thanks so much for your effort and contributions!

2024-12-24 13:22 UTC, twisst commented
> Hey @twisst I think you might have included these changes in the "fixes Facebook link in footer" PR by mistake.
Hi @SableRaf, yeah I noticed. I was already looking at the [scary Github magic](https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request) required. I'll give it a try.

> In fact, most of these changes can't be made directly in the website repository anyway.
Ouch. Oh well, I'll just consider it good practice :-) 
 
> Thanks so much for your effort and contributions!
Glad to help!

2025-01-14 17:17 UTC, SableRaf requested changes

2025-01-14 17:17 UTC, SableRaf commented on src/components/Footer.js
> +            <a href={'https://www.facebook.com/page.processing/'} target="_blank" rel="noreferrer">Facebook</a>
The link should be https://www.facebook.com/people/Processing-Core/61567491443061/

2025-01-27 12:55 UTC, merged